name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: skipping
        env:
          skip: ${{ contains(join(github.event.commits.*.message), '#skip') }}
        if: ${{ env.skip == true }}
        run: echo "skipped"
      - name: test join
        env:
          joined_messages: ${{ join(github.event.commits.*.message) }}
        run: echo "$joined_messages"
      - name: not skipping
        env:
          no_skip: ${{ contains(join(github.event.commits.*.message), '#skip') }}
        if: env.no_skip == false
        run: echo "not skipped"
      - name: test contains
        env:
          myContains: ${{ contains(join(github.events.commits.*.message), 'testaus') }}
        run: echo "myContains"
